### ISSUE TITLE
文章列表页面切换 page=NaN

### ISSUE THREAD

**Issue by Adkimsm** [nx-space/nx-theme-tiny#10]
https://blog.iucky.cn/posts?page=2

在这个页面中，上一页的按钮指向错误的 `/posts?page=NaN`.

**Comment by wibus-wee** [comment]
心急导致改错了 😂

https://github.com/nx-space/nx-theme-tiny/blob/main/pages/posts/index.tsx#L97-L97

这个地方应该是 current_page 的

**Comment by wibus-wee** [comment]
还还还没改（）
